name: Gradle Wrapper Validation
on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  validate-project-gradle-wrapper:
    if: ${{ github.repository == 'MiSikora/Ruler' }}
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
