name: Gradle Wrapper Validation
on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  validate-project-gradle-wrapper:
    if: ${{ github.repository == 'MiSikora/ruler' }}
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3.1.0

      - name: Configure JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: adopt
          java-version: 16

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
