name: Quality Check
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'library/docs/**'
      - '**.md'
      - '.github/CODEOWNERS'
  pull_request:
    paths-ignore:
      - 'library/docs/**'
      - '**.md'
      - '.github/CODEOWNERS'

jobs:
  android-tests:
    if: ${{ github.repository == 'MiSikora/ruler' }}
    name: Android Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Configure JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 16

      - name: Cache Gradle Dirs
        uses: actions/cache@v3.0.3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2.22.0
        with:
          api-level: 29
          emulator-build: 6110076
          script: ./gradlew connectedCheck --stacktrace
        env:
          API_LEVEL: 29

      - name: Stop Gradle
        run: ./gradlew --stop

  tests:
    if: ${{ github.repository == 'MiSikora/ruler' }}
    name: JVM Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0

      - name: Configure JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 16

      - name: Cache Gradle Dirs
        uses: actions/cache@v3.0.3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Tests
        run: ./gradlew test --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop

  detekt:
    if: ${{ github.repository == 'MiSikora/ruler' }}
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0

      - name: Configure JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 16

      - name: Cache Gradle Dirs
        uses: actions/cache@v3.0.3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Detekt
        run: ./gradlew detekt --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop

  lint:
    if: ${{ github.repository == 'MiSikora/ruler' }}
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0

      - name: Configure JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 16

      - name: Cache Gradle Dirs
        uses: actions/cache@v3.0.3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Run Lint
        run: ./gradlew lint --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop

  binary-compatibility:
    if: ${{ github.repository == 'MiSikora/ruler' }}
    name: Binary compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0

      - name: Configure JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 16

      - name: Cache Gradle Dirs
        uses: actions/cache@v3.0.3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: cache-gradle-

      - name: Check ABI
        run: ./gradlew apiCheck --stacktrace

      - name: Stop Gradle
        run: ./gradlew --stop
